
import { TemplateData } from "./types";

export const templateData: TemplateData[] = [
  {
    id: "verificador-cumplimiento",
    title: "Verificador de cumplimiento normativo",
    description: "Comprueba en 2 minutos si tu empresa cumple con la normativa de registro horario y calcula posibles sanciones.",
    imageSrc: "/lovable-uploads/654278fc-cbcc-4b9d-8b9a-0a7065e56d8d.png",
    category: "Normativa Laboral",
    action: "edit",
    actionLabel: "Iniciar verificación",
    editUrl: "/plantillas/verificador-cumplimiento",
    baseDownloads: 3412,
    metaDescription: "Verifica gratis si tu empresa cumple la normativa de registro horario. Test de 10 preguntas con calculadora de sanciones.",
  },
  {
    id: "planificador-turnos",
    title: "Planificador visual de turnos rotativos",
    description: "Organiza los turnos de tu equipo con rotación automática, vista semanal/mensual y control de horas por empleado.",
    imageSrc: "/lovable-uploads/d48380f9-f5c9-4f3f-8184-8ef27150846d.png",
    category: "Turnos",
    action: "edit",
    actionLabel: "Usar planificador",
    editUrl: "/plantillas/planificador-turnos",
    baseDownloads: 1563,
    metaDescription: "Planifica turnos rotativos gratis con esta herramienta visual. Rotación automática, vista semanal y mensual, y resumen de horas.",
  },
  {
    id: "guia-talento",
    title: "Guía de talento: desempeño y seguimiento de objetivos",
    description: "Herramienta interactiva para evaluar el desempeño, planificar formaciones y realizar seguimiento de objetivos.",
    imageSrc: "/lovable-uploads/91e7dd43-1049-45fc-ae3d-b7ecbd608938.png",
    category: "Evaluación",
    action: "edit",
    actionLabel: "Usar plantilla",
    editUrl: "/plantillas/guia-talento",
    baseDownloads: 1247,
    metaDescription: "Evalúa el desempeño de tu equipo y haz seguimiento de objetivos con esta guía interactiva gratuita. Adaptada a empresas españolas.",
  },
  {
    id: "registro-horas-trabajadas",
    title: "Registro de horas trabajadas - Timecard para empleados",
    description: "Herramienta completa para el control diario, semanal, mensual y anual de las horas laborales de los trabajadores.",
    imageSrc: "/lovable-uploads/4efc5a5e-0fc6-450c-8097-471f8f05bcd9.png",
    category: "Control horario",
    action: "edit",
    actionLabel: "Ver recurso",
    editUrl: "/plantillas/registro-horas",
    baseDownloads: 2384,
    metaDescription: "Registra las horas trabajadas de tus empleados con esta herramienta gratuita. Control diario, semanal y mensual conforme a la normativa española.",
  },
  {
    id: "kit-herramientas-ley",
    title: "Quickstart legal para registro horario",
    description: "Genera automáticamente el comunicado legal, acuerdo con representantes y protocolo de registro horario.",
    imageSrc: "/lovable-uploads/d48380f9-f5c9-4f3f-8184-8ef27150846d.png",
    category: "Normativa Laboral",
    action: "external",
    actionLabel: "Generar documentación",
    editUrl: "https://comunicado-legal.inwout.app",
    baseDownloads: 876,
    metaDescription: "Genera la documentación legal obligatoria para el registro horario: comunicado, acuerdo con representantes y protocolo.",
  },
  {
    id: "plantilla-onboarding",
    title: "Plantilla de onboarding para nuevas incorporaciones",
    description: "Guía paso a paso para garantizar una incorporación efectiva de nuevos empleados.",
    imageSrc: "/lovable-uploads/d6062b36-0681-45de-b8e9-c72886e9b4eb.png",
    category: "Onboarding",
    action: "download",
    actionLabel: "Descargar PDF",
    downloadUrl: "#",
    baseDownloads: 643,
    metaDescription: "Descarga gratis esta plantilla de onboarding para nuevas incorporaciones. Checklist paso a paso para RRHH.",
  },
  {
    id: "modelo-evaluacion-competencias",
    title: "Modelo de evaluación por competencias",
    description: "Formato estructurado para evaluar las competencias profesionales de tu equipo.",
    imageSrc: "/lovable-uploads/c5c2388b-0353-48bf-b9e7-a1f741ad108b.png",
    category: "Evaluación",
    action: "download",
    actionLabel: "Descargar PDF",
    downloadUrl: "#",
    baseDownloads: 512,
    metaDescription: "Modelo gratuito de evaluación por competencias para RRHH. Formato profesional y listo para usar.",
  },
  {
    id: "descripcion-puestos",
    title: "Plantilla para la descripción de puestos",
    description: "Documento para definir con claridad las responsabilidades de cada puesto de trabajo.",
    imageSrc: "/lovable-uploads/dfe6d0a8-a218-4527-9602-1b4165cbe731.png",
    category: "Productividad",
    action: "download",
    actionLabel: "Descargar DOCX",
    downloadUrl: "#",
    baseDownloads: 1089,
    metaDescription: "Plantilla gratuita para describir puestos de trabajo. Define responsabilidades, requisitos y competencias.",
  },
  {
    id: "control-ausencias",
    title: "Plantilla para control de ausencias justificadas",
    description: "Registro de ausencias laborales con motivos y documentación justificativa.",
    imageSrc: "/lovable-uploads/bfe02090-bf42-4aa1-a40b-853d59bbf5e7.png",
    category: "Control horario",
    action: "download",
    actionLabel: "Descargar Excel",
    downloadUrl: "#",
    baseDownloads: 1756,
    metaDescription: "Controla las ausencias de tu equipo con esta plantilla Excel gratuita. Incluye motivos y documentación justificativa.",
  },
  {
    id: "acta-reunion-equipos",
    title: "Ejemplo de acta de reunión para equipos remotos",
    description: "Formato optimizado para documentar reuniones y acuerdos en entornos de trabajo remoto.",
    imageSrc: "/lovable-uploads/ba53c58c-1385-4d44-85fe-bcaca97175b4.png",
    category: "Comunicación Interna",
    action: "download",
    actionLabel: "Descargar PDF",
    downloadUrl: "#",
    baseDownloads: 438,
    metaDescription: "Acta de reunión para equipos remotos. Formato profesional para documentar acuerdos y seguimiento.",
  },
  {
    id: "calendario-rrhh-2026",
    title: "Calendario anual editable para planificación de RRHH",
    description: "Calendario anual para la planificación de vacaciones, formaciones y eventos de empresa.",
    imageSrc: "/lovable-uploads/afe2beb8-a0b8-4bb7-8a23-e7ead8320fd4.png",
    category: "Productividad",
    action: "download",
    actionLabel: "Descargar Excel",
    downloadUrl: "#",
    baseDownloads: 1923,
    metaDescription: "Calendario RRHH 2026 editable y gratuito. Planifica vacaciones, formaciones y eventos de empresa.",
  },
  {
    id: "encuesta-clima-laboral",
    title: "Encuesta de clima laboral",
    description: "Cuestionario para evaluar la satisfacción y el ambiente de trabajo en tu organización.",
    imageSrc: "/lovable-uploads/3cd4bb17-0813-45c8-8472-c691355116b5.png",
    category: "Comunicación Interna",
    action: "download",
    actionLabel: "Descargar PDF",
    downloadUrl: "#",
    baseDownloads: 689,
    metaDescription: "Encuesta de clima laboral gratuita. Evalúa la satisfacción y el ambiente de trabajo de tu equipo.",
  },
  {
    id: "guia-planificacion-formaciones",
    title: "Guía de planificación de formaciones trimestrales",
    description: "Estructura para organizar un plan de formación efectivo para tu equipo.",
    imageSrc: "/lovable-uploads/dd574472-7de1-4a79-98a7-2f1bdae617ff.png",
    category: "Formación",
    action: "download",
    actionLabel: "Descargar PDF",
    downloadUrl: "#",
    baseDownloads: 374,
    metaDescription: "Planifica las formaciones de tu equipo con esta guía trimestral gratuita. Estructura y calendario incluidos.",
  },
  {
    id: "seguimiento-tareas",
    title: "Hoja de seguimiento de tareas por empleado",
    description: "Plantilla para realizar un seguimiento eficaz de las tareas asignadas a cada miembro del equipo.",
    imageSrc: "/lovable-uploads/d4bb9d25-d564-497f-8477-748edb23ed0e.png",
    category: "Productividad",
    action: "download",
    actionLabel: "Descargar Excel",
    downloadUrl: "#",
    baseDownloads: 821,
    metaDescription: "Hoja de seguimiento de tareas por empleado. Plantilla Excel gratuita para gestionar la productividad.",
  }
];
